# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

SourceItaly.delete_all
SourceFrance.delete_all
#Stock.delete_all

#Cac40Report.delete_all
#Dax30Report.delete_all
#FiasReport.delete_all

#User.delete_all
#UserReport.delete_all

#Market.delete_all
#Analysis.delete_all

#Other tables
#follow_stock_newsletters
#followers
#friendly_id_slugs
#market_suggestions_newsletters

###Source Italy###
sourceitaly_list = [
  ["IT0001233417", "A2a", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0001233417.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/9.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001233417&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=A2A.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=A2A.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=00c0&codicestrumento=w2ae&DBCOD=A2A", "https://www.teleborsa.it/azioni/a2a-a2a-it0001233417-SVQwMDAxMjMzNDE3/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/a2a-2ae00c0"],
  ["IT0004056880", "Amplifon", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0004056880.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/525.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004056880&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=AMP.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=AMP.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=01ef&codicestrumento=w2ae&DBCOD=AMP", "https://www.teleborsa.it/azioni/amplifon-amp-it0004056880-SVQwMDA0MDU2ODgw/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/amplifon-2ae01ef"],
  ["IT0003506190", "Atlantia", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0003506190.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/23.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003506190&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=ATL.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=ATL.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=003b&codicestrumento=w2ae&DBCOD=ATL", "https://www.teleborsa.it/azioni/atlantia-atl-it0003506190-SVQwMDAzNTA2MTkw/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/atlantia-2ae003b"],
  ["IT0003261697", "Azimut Holding", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0003261697.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/718.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003261697&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=AZM.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=AZM.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=03ba&codicestrumento=w2ae&DBCOD=AZM", "https://www.teleborsa.it/azioni/azimut-azm-it0003261697-SVQwMDAzMjYxNjk3/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/azimut-2ae03ba"],
  ["IT0005218380", "Banco Bpm", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0005218380.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/1928.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0005218380&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=BAMI.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=BAMI.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=10a2&codicestrumento=w2ae&DBCOD=BAMI", "https://www.teleborsa.it/azioni/banco-bpm-bami-it0005218380-SVQwMDA1MjE4Mzgw/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/banco-bpm-2ae10a2"],
  ["IT0000066123", "Bper Banca", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0000066123.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/43.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0000066123&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=BPE.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=BPE.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=006e&codicestrumento=w2ae&DBCOD=BPE", "https://www.teleborsa.it/azioni/bper-bpe-it0000066123-SVQwMDAwMDY2MTIz/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/bper-banca-2ae006e"],
  ["IT0001347308", "Buzzi Unicem", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0001347308.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/77.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001347308&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=BZU.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=BZU.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0013&codicestrumento=w2ae&DBCOD=BZU", "https://www.teleborsa.it/azioni/buzzi-unicem-bzu-it0001347308-SVQwMDAxMzQ3MzA4/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/buzzi-unicem-2ae0013"],
  ["IT0005252207", "Campari", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0005252207.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/530.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0005252207&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=CPR.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=CPR.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=01f2&codicestrumento=w2ae&DBCOD=CPR", "https://www.teleborsa.it/azioni/campari-cpr-it0005252207-SVQwMDA1MjUyMjA3/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/campari-2ae01f2"],
  ["NL0010545661", "Cnh Industrial", "https://www.borsaitaliana.it/borsa/azioni/scheda/NL0010545661.html?lang=it", "", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=NL0010545661&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=CNHI.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=CNHI.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=1025&codicestrumento=w2ae&DBCOD=CNHI", "https://www.teleborsa.it/azioni/cnh-industrial-cnhi-nl0010545661-TkwwMDEwNTQ1NjYx/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/cnh-industrial-2ae1025"],

  ["IT0003492391", "Diasorin", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0003492391.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/957.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003492391&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=DIA.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=DIA.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0449&codicestrumento=w2ae&DBCOD=DIA", "https://www.teleborsa.it/azioni/diasorin-dia-it0003492391-SVQwMDAzNDkyMzkx/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/diasorin-2ae0449"],
  ["IT0003128367", "Enel", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0003128367.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/116.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003128367&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=ENEL.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=ENEL.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=008b&codicestrumento=w2ae&DBCOD=ENEL", "https://www.teleborsa.it/azioni/enel-enel-it0003128367-SVQwMDAzMTI4MzY3/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/enel-2ae008b"],
  ["IT0003132476", "Eni", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0003132476.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/117.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003132476&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=ENI.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=ENI.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0017&codicestrumento=w2ae&DBCOD=ENI", "https://www.teleborsa.it/azioni/eni-eni-it0003132476-SVQwMDAzMTMyNDc2/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/eni-2ae0017"],
  ["NL0012059018", "Exor", "https://www.borsaitaliana.it/borsa/azioni/scheda/NL0012059018.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/1920.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=NL0012059018&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=EXO.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=EXO.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=010d&codicestrumento=w2ae&DBCOD=EXO", "https://www.teleborsa.it/azioni/exor-exo-nl0012059018-TkwwMDEyMDU5MDE4/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/exor-2ae010d"],
  ["NL0011585146", "Ferrari", "https://www.borsaitaliana.it/borsa/azioni/scheda/NL0011585146.html?lang=it", "", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=NL0011585146&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=RACE.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=RACE.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=106d&codicestrumento=w2ae&DBCOD=RACE", "https://www.teleborsa.it/azioni/ferrari-race-nl0011585146-TkwwMDExNTg1MTQ2/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/ferrari-2ae106d"],
  ["NL0010877643", "Fiat Chrysler Automobiles", "https://www.borsaitaliana.it/borsa/azioni/scheda/NL0010877643.html?lang=it", "", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=NL0010877643&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=FCA.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=FCA.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=00be&codicestrumento=w2ae&DBCOD=FCA", "https://www.teleborsa.it/azioni/fiat-chrysler-automobiles-fca-nl0010877643-TkwwMDEwODc3NjQz/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/fiat-chrysler-automobiles-2ae00be"],
  ["IT0000072170", "Finecobank", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0000072170.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/1615.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0000072170&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=FBK.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=FBK.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=103d&codicestrumento=w2ae&DBCOD=FBK", "https://www.teleborsa.it/azioni/finecobank-fbk-it0000072170-SVQwMDAwMDcyMTcw/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/finecobank-2ae103d"],
  ["IT0000062072", "Generali Ass", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0000062072.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/18.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0000062072&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=G.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=G.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=00e5&codicestrumento=w2ae&DBCOD=G", "https://www.teleborsa.it/azioni/generali-g-it0000062072-SVQwMDAwMDYyMDcy/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/generali-ass-2ae00e5"],
  ["IT0001250932", "Hera", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0001250932.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/661.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0001250932&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=HER.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=HER.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=039e&codicestrumento=w2ae&DBCOD=HER", "https://www.teleborsa.it/azioni/hera-her-it0001250932-SVQwMDAxMjUwOTMy/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/hera-2ae039e"],
  ["IT0000072618", "Intesa Sanpaolo", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0000072618.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/33.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0000072618&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=ISP.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=ISP.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0056&codicestrumento=w2ae&DBCOD=ISP", "https://www.teleborsa.it/azioni/intesa-sanpaolo-isp-it0000072618-SVQwMDAwMDcyNjE4/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/intesa-sanpaolo-2ae0056"],
  ["IT0005211237", "Italgas", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0005211237.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/167.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0005211237&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=IG.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=IG.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=109f&codicestrumento=w2ae&DBCOD=IG", "https://www.teleborsa.it/azioni/italgas-ig-it0005211237-SVQwMDA1MjExMjM3/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/italgas-2ae109f"],

  ["IT0000336518", "Juventus Fc", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0000336518.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/546.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0000336518&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=JUVE.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=JUVE.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0366&codicestrumento=w2ae&DBCOD=JUVE", "https://www.teleborsa.it/azioni/juventus-fc-juve-it0000336518-SVQwMDAwMzM2NTE4/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/juventus-fc-2ae0366"],
  ["IT0003856405", "Leonardo", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0003856405.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/131.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003856405&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=LDO.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=LDO.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=00b2&codicestrumento=w2ae&DBCOD=LDO", "https://www.teleborsa.it/azioni/leonardo-ldo-it0003856405-SVQwMDAzODU2NDA1/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/leonardo-2ae00b2"],
  ["IT0000062957", "Mediobanca", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0000062957.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/187.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0000062957&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=MB.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=MB.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=011d&codicestrumento=w2ae&DBCOD=MB", "https://www.teleborsa.it/azioni/mediobanca-mb-it0000062957-SVQwMDAwMDYyOTU3/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/mediobanca-2ae011d"],
  ["IT0004965148", "Moncler", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0004965148.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/1218.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004965148&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=MONC.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=MONC.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=1029&codicestrumento=w2ae&DBCOD=MONC", "https://www.teleborsa.it/azioni/moncler-monc-it0004965148-SVQwMDA0OTY1MTQ4/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/moncler-2ae1029"],
  ["IT0005366767", "Nexi", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0005366767.html?lang=it", "", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0005366767&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=NEXI.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=NEXI.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=1114&codicestrumento=w2ae&DBCOD=NEXI", "https://www.teleborsa.it/azioni/nexi-nexi-it0005366767-SVQwMDA1MzY2NzY3/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/nexi-2ae1114"],
  ["IT0005278236", "Pirelli & C", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0005278236.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/206.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0005278236&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=PIRC.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=PIRC.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=10bc&codicestrumento=w2ae&DBCOD=PIRC", "https://www.teleborsa.it/azioni/pirelli-c-pirc-it0005278236-SVQwMDA1Mjc4MjM2/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/pirelli-c-2ae10bc"],
  ["IT0003796171", "Poste Italiane", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0003796171.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/1130.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003796171&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=PST.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=PST.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=1064&codicestrumento=w2ae&DBCOD=PST", "https://www.teleborsa.it/azioni/poste-italiane-pst-it0003796171-SVQwMDAzNzk2MTcx/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/poste-italiane-2ae1064"],
  ["IT0004176001", "Prysmian", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0004176001.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/902.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004176001&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=PRY.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=PRY.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=041e&codicestrumento=w2ae&DBCOD=PRY", "https://www.teleborsa.it/azioni/prysmian-pry-it0004176001-SVQwMDA0MTc2MDAx/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/prysmian-2ae041e"],
  ["IT0003828271", "Recordati Ord", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0003828271.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/216.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003828271&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=REC.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=REC.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=01cd&codicestrumento=w2ae&DBCOD=REC", "https://www.teleborsa.it/azioni/recordati-rec-it0003828271-SVQwMDAzODI4Mjcx/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/recordati-ord-2ae01cd"],
  ["IT0005252140", "Saipem", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0005252140.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/232.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0005252140&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=SPM.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=SPM.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0193&codicestrumento=w2ae&DBCOD=SPM", "https://www.teleborsa.it/azioni/saipem-spm-it0005252140-SVQwMDA1MjUyMTQw/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/saipem-2ae0193"],
  ["IT0004712375", "Salvatore Ferragamo", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0004712375.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/1220.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004712375&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=SFER.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=SFER.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0049&codicestrumento=w2ae&DBCOD=SFER", "https://www.teleborsa.it/azioni/salvatore-ferragamo-sfer-it0004712375-SVQwMDA0NzEyMzc1/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/salvatore-ferragamo-2ae0049"],
  ["IT0003153415", "Snam", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0003153415.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/542.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003153415&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=SRG.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=SRG.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0363&codicestrumento=w2ae&DBCOD=SRG", "https://www.teleborsa.it/azioni/snam-srg-it0003153415-SVQwMDAzMTUzNDE1/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/snam-2ae0363"],
  ["NL0000226223", "Stmicroelectronics", "https://www.borsaitaliana.it/borsa/azioni/scheda/NL0000226223.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/253.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=NL0000226223&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=STM.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=STM.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0022&codicestrumento=w2ae&DBCOD=STM", "https://www.teleborsa.it/azioni/stmicroelectronics-stm-nl0000226223-TkwwMDAwMjI2MjIz/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/stmicroelectronics-2ae0022"],
  ["IT0003497168", "Telecom Italia", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0003497168.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/156.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003497168&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=TIT.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=TIT.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0098&codicestrumento=w2ae&DBCOD=TIT", "https://www.teleborsa.it/azioni/telecom-italia-tit-it0003497168-SVQwMDAzNDk3MTY4/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/telecom-italia-2ae0098"],
  ["LU0156801721", "Tenaris", "https://www.borsaitaliana.it/borsa/azioni/scheda/LU0156801721.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/602.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=LU0156801721&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=TEN.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=TEN.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0383&codicestrumento=w2ae&DBCOD=TEN", "https://www.teleborsa.it/azioni/tenaris-ten-lu0156801721-TFUwMTU2ODAxNzIx/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/tenaris-2ae0383"],
  ["IT0003242622", "Terna", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0003242622.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/720.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003242622&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=TRN.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=TRN.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=03b7&codicestrumento=w2ae&DBCOD=TRN", "https://www.teleborsa.it/azioni/terna-trn-it0003242622-SVQwMDAzMjQyNjIy/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/terna-2ae03b7"],
  ["IT0003487029", "Ubi Banca", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0003487029.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/665.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0003487029&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=UBI.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=UBI.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=039f&codicestrumento=w2ae&DBCOD=UBI", "https://www.teleborsa.it/azioni/ubi-ubi-it0003487029-SVQwMDAzNDg3MDI5/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/ubi-banca-2ae039f"],
  ["IT0005239360", "Unicredit", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0005239360.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/263.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0005239360&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=UCG.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=UCG.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0096&codicestrumento=w2ae&DBCOD=UCG", "https://www.teleborsa.it/azioni/unicredit-ucg-it0005239360-SVQwMDA1MjM5MzYw/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/unicredit-2ae0096"],
  ["IT0004810054", "Unipol", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0004810054.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/265.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004810054&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=UNI.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=UNI.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=002b&codicestrumento=w2ae&DBCOD=UNI", "https://www.teleborsa.it/azioni/unipol-uni-it0004810054-SVQwMDA0ODEwMDU0/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/unipol-2ae002b"],
  ["IT0004827447", "Unipolsai", "https://www.borsaitaliana.it/borsa/azioni/scheda/IT0004827447.html?lang=it", "https://www.borsaitaliana.it/companyprofile/htm/it/230.htm", "https://www.borsaitaliana.it/borsa/azioni/analisi-tecnica.html?isin=IT0004827447&lang=it", "https://vwd-proxy.ilsole24ore.com/FinanzaMercati/WidgetSelector/box-commento?widgetConfiguration=BoxCommentoBilancioSintetico&topicName=US.MI", "https://mercatiwdg.ilsole24ore.com/FinanzaMercati/WidgetSelector/analisi-tecnica-dettaglio?topicName=US.MI", "https://www.milanofinanza.it/mercati/analisi-tecnica?mercato=italiano&stockcodert=0126&codicestrumento=w2ae&DBCOD=US", "https://www.teleborsa.it/azioni/unipolsai-us-it0004827447-SVQwMDA0ODI3NDQ3/analisi?tab=2", "https://www.milanofinanza.it/quotazioni/dettaglio/unipolsai-2ae0126"],

]

sourceitaly_list.each do |isin, name, url_0, url_1, url_2, url_3, url_4, url_5, url_6, url_7|
  SourceItaly.create(isin: isin, name: name, url_0: url_0, url_1: url_1, url_2: url_2, url_3: url_3, url_4: url_4, url_5: url_5, url_6: url_6, url_7: url_7)
end
###Source Italy###

###Source France###
sourcefrance_list = [
  ["FR0000120321", "L&apos;Oreal", "https://www.tradingsat.com/loreal-FR0000120321/societe.html", "https://www.tradingsat.com/loreal-FR0000120321/", "https://bourse.fortuneo.fr/api/value/trends/ACTIONS/FTN000023FR0000120321", "https://bourse.fortuneo.fr/api/value/performance-periods/ACTIONS/FTN000023FR0000120321", "http://bourse.lefigaro.fr/indices-actions/cours-l-oreal-or-fr0000120321-par", "http://tradingradar.net/fr", "https://bourse.fortuneo.fr/api/value/avis/FTN000023FR0000120321"],
  ["FR0000120073", "Air Liquide", "https://www.tradingsat.com/air-liquide-FR0000120073/societe.html", "https://www.tradingsat.com/air-liquide-FR0000120073/", "https://bourse.fortuneo.fr/api/value/trends/ACTIONS/FTN000023FR0000120073", "https://bourse.fortuneo.fr/api/value/performance-periods/ACTIONS/FTN000023FR0000120073", "http://bourse.lefigaro.fr/indices-actions/cours-air-liquide-ai-fr0000120073-par", "http://tradingradar.net/fr", "https://bourse.fortuneo.fr/api/value/avis/FTN000023FR0000120073"],
]

sourcefrance_list.each do |isin, name, url_0, url_1, url_2, url_3, url_4, url_5, url_6|
  SourceFrance.create(isin: isin, name: name, url_0: url_0, url_1: url_1, url_2: url_2, url_3: url_3, url_4: url_4, url_5: url_5, url_6: url_6)
end
###Source France###

###Market###
#Markets are ordered by id in the top section
market_list = [
  ["FTSE MIB", "", "", "italy"],
  ["CAC 40", "", "", "france"],
]

market_list.each do |name, value, variation, country|
  #Market.create(name: name, value: value, variation: variation, country: country)
end
###Market###
